# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - shoesapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://shoesapp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_53a733a75a41446e846724b22d26f2f7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_47ad9c19b25d4542a020d23db2c98c97 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: shoesapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_53a733a75a41446e846724b22d26f2f7 }}/shoesclassification:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'shoesapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_04d98ca531e64ac8b4dc0f892be19dc0 }}
        images: 'shoesapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_53a733a75a41446e846724b22d26f2f7 }}/shoesclassification:${{ github.sha }}'